module.exports = [
  { class: 'red', type: 'open', match: 'r[', },
  { class: 'red', type: 'close', match: ']r', },
  { class: 'green', type: 'open',  match: 'g[', },
  { class: 'green', type: 'close', match: ']g', },
  { class: 'yellow', type: 'open', match: 'y[' },
  { class: 'yellow', type: 'close', match: ']y' },  
  { class: 'blue', type: 'open', match: 'b[' },
  { class: 'blue', type: 'close', match: ']b' },  
  { class: 'lime', type: 'open', match: 'l[' },
  { class: 'lime', type: 'close', match: ']l' },  
  { class: 'orange', type: 'open', match: 'o[' },
  { class: 'orange', type: 'close', match: ']o' },  
  { class: 'pink', type: 'open', match: 'p[' },
  { class: 'pink', type: 'close', match: ']p' },  
  { class: 'bold', type: 'open', match: '*[' },
  { class: 'bold', type: 'close', match: ']*' },
  { class: 'underline', type: 'open', match: '_[' },
  { class: 'underline', type: 'close', match: ']_' },
  { class: 'italic', type: 'open', match: '/[' },
  { class: 'italic', type: 'close', match: ']/' },
  { class: 'big', type: 'open', match: '^[' },
  { class: 'big', type: 'close', match: ']^' },
  { class: 'small', type: 'open', match: '.[' },
  { class: 'small', type: 'close', match: '].' },                
]
